#!/bin/bash

objects=""
rules=""

for file in *.cc; do
  obj="bin/${file/%cc/o}"
  objects="$objects $obj"
  dependency=$(g++ -MM -MT "$obj" -std=c++11 $file)
  dependency=$(echo $dependency | sed 's/ \\//g')
  rule=$(printf '%s\n\t$(CC) $(CFLAGS) %s -o %s' "$dependency" "$file" "$obj")
  rules=$(printf '%s\n\n%s' "$rules" "$rule")
done

if [ -f makefile ]; then
  echo "makefile already exists - stopping"
  exit 1
fi

echo 'CC=g++' >> makefile
echo >> makefile
echo 'CFLAGS=-Wall -c -std=c++11' >> makefile
echo >> makefile
echo "OBJ=$objects" >> makefile
echo >> makefile
printf '%s\n\n%s\n\t%s' 'all: $(OBJ)' 'clean:' 'rm -rf $(OBJ)' >> makefile
echo "$rules" >> makefile

make $1

rm makefile
