#!/bin/bash

objects=""
binaries=""
rules=""

for file in *.cc; do
  obj="bin/${file/%cc/o}"
  objects="$objects $obj"
  dependency=$(g++ -MM -MT "$obj" -std=c++11 $file)
  dependency=$(echo $dependency | sed 's/ \\//g')
  rule=$(printf '%s\n\t$(CC) $(CFLAGS) %s -o %s' "$dependency" "$file" "$obj")
  rules=$(printf '%s\n\n%s' "$rules" "$rule")
done

for file in examples/*.cc; do
  binary="bin/${file/%cc/exe}"
  binaries="$binaries $binary"
  rule=$(printf '%s: %s %s\n\t%s %s %s %s' "$binary" "$file" '$(OBJ)' '$(CC) \
       $(LINKFLAGS)' "$file" '$(OBJ)' "-o $binary")
  rules=$(printf '%s\n\n%s' "$rules" "$rule")
done

echo 'CC=g++' > makefile
echo >> makefile
echo 'CFLAGS=-Wall -c -std=c++11' >> makefile
echo 'LINKFLAGS=-Wall -std=c++11' >> makefile
echo >> makefile
echo "OBJ=$objects" >> makefile
echo "BIN=$binaries" >> makefile
echo >> makefile
printf '%s\n\n%s\n\t%s' 'all: $(OBJ) $(BIN)' 'clean:' 'rm -rf $(OBJ) $(BIN)' >> makefile
echo "$rules" >> makefile

make $1
